---
output_dir: output/blog
data_sources:
- type: filesystem_unified
  items_root: /
  layouts_root: /
enable_output_diff: false
base_url: http://localhost:3000
google_analytics:
  domain: 
  site_id: 
clicky_analytics:
  site_id: 66503113
site_name: bl[:)g
featured_count: 0
excerpt_count: 6
other_articles_max: 1
include_disqus_js: false
disqus_shortname: eyeshalfclosed
ultraviolet_theme: sunburst
deploy:
  default:
    dst_remote: origin
    dst_branch: gh-pages
    src_branch: master
